aworld/urls.py
from django.urls import path 
from .views import *

app_name = 'aworld'


urlpatterns = [
   path('',IndexView.as_view() , name='index'),
   path('contact/',ContactView, name="contact"),
   path('about/',AboutView.as_view() , name='about'),
   path('gallery/',GalleryView.as_view() , name='gallery'),
   path('service/',ServiceView.as_view() , name='service'),
   
]

homes/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aworld.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

aworld/models.py
from django.db import models
from django.urls import reverse
from cloudinary.models import CloudinaryField

# Create your models here.

class Gallery(models.Model):
    image = CloudinaryField('image')
    type_of_image = models.CharField(max_length=50 , null=True)
    content = models.CharField(max_length=200 , null=True)
    


    def __str__(self):  
        return self.type_of_image 

aworld/views.py
from django.shortcuts import  render 
from .models import *
from django.core.mail import message, send_mail
from django.views.generic import *

from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
class IndexView(TemplateView):
    template_name = 'aworld/index.html'

#===========================contact view===============================

def ContactView(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        comment = request.POST.get('comment')
        email = request.POST.get('email')
      
        
        send_mail(
            fname,
            comment,
            email,
            ['greenerhomes2020@gmail.com'],
            fail_silently=False,
            )
        return render(request,'aworld/email_sent.html',{'email':email})  
    return render(request,'aworld/contact.html',{})

#============================ABOUT VIEW===================================
class AboutView(TemplateView):
    template_name = 'aworld/about.html'  


#=====================================gALLERY vIEW===================================
class GalleryView(ListView):
    context_object_name = 'gallery'
    template_name = 'aworld/gallery.html'
    model = Gallery


class ServiceView(TemplateView):
    template_name = 'aworld/service.html' 

aworld/templates/aworld/about.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<style>
    *{
        text-decoration: none;
    }
    #enroll{
   background: url("/static/images/image-5.jpg");
   background-attachment: fixed;
   background-position: center;
   block-size: cover;
   background-repeat: no-repeat;
   background-size:cover;
   box-shadow:inset 0 0 0 2000px rgba(0,0,0,0.4);
   padding: 80px 0px;
   height: 400px;
  
  }

 #enroll h5{
    font-size: 20px;
    font-family: 'Castoro', serif;
    letter-spacing: 2;
    color:rgb(241, 145, 0) !important;
 }
 #enroll h5 a{
    text-decoration: none;
    color: #fff !important;
 }
 /* ============our servuce ================ */
 #service h2::after{
    content: " ";
    display:block; /* So we can set a width */
    width: 85px;
    height: 5px;
    border-radius: 50px;
    background-color: rgb(241, 145, 0);
    margin-top: 8px;
}
.box{
    border: 3px solid rgb(182, 182, 182);  
}
/* =================our vision=================== */
.tesimony{
   /* Permalink - use to edit and share this gradient: https://colorzilla.com/gradient-editor/#ffa84c+0,ff7b0d+100;Orange+3D */
    background: #fff; /* Old browsers */
    background: -moz-linear-gradient(-45deg,  #fff 0%, #fff 100%); /* FF3.6-15 */
    background: -webkit-linear-gradient(-45deg,  #fff 0%,#fff 100%); /* Chrome10-25,Safari5.1-6 */
    background: linear-gradient(135deg,  #fff 0%,#fff 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffa84c', endColorstr='#ff7b0d',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
     padding:15px;
     width: fit-content;
   

     box-shadow: 10px 10px 5px -8px rgba(0,0,0,0.75);
    -webkit-box-shadow: 10px 10px 5px -8px rgba(0,0,0,0.75);
    -moz-box-shadow: 10px 10px 5px -8px rgba(0,0,0,0.75);


 }
 /* ==== */
 
   
</style>


<!-- =============== -->
<div class="row mb-4 justify-content-center text-center">
    <div class="col-sm-12 " id="enroll">
      <div class="con-2 pt-5">
      <h3 class="text-light text-center lg-mt-5 text-justify " style="font-size: 30px;"> About Us</h3>
     <h5 class=" text-light" style="width: 70%; margin:auto;"> <a href="{% url 'aworld:index' %}">Home</a> |  About</h5>
      </div>
    </div>
</div>
<!-- ====================our story=================================== -->
<div class="container p-5">
    <div class="row mb-4">
        <div class="col-sm-12 col-md-8  py-3" id="service">
            <h2 class="my-3">Our Story</h2>
            <p class="text-justify " style="letter-spacing: 2;"> <b><i>AWORLD GREENER HOMES</i></b> is an Interior Design, Decoration and Real Estate company that specializes in furnishing homes and workplaces with semi-heavy and light furnishing materials. AWORLD GREENER HOMES offers the sales and supply of decorative and furnishing materials to clients and potential customers of the most valuable, reliable, durable, accessible, magnificent and elegant materials. We offer top-notch products and services to bring about the most luxurious, cosy furnishings for the real comfort and satisfaction of clients and sundry customers thereby ending their long awaited frustrations and deprivations towards embracing their dream homes and workplaces through our expert service,</p>

            <p class="text-justify" style="letter-spacing: 2;"> we deliver on all budgets by our broad management approach no matter how meagre your budget is we are poised to giving you the best by arriving at the same results just as in bogus budgets through innovation and creativity, bringing the most appealing and inviting ambience to your home or work place. AG Homes have answers to every home interior needs and this is made possible by our management skills and team of experts. Our versatility in this industry and in real estate business is quite encompassing to meet the interior needs of clients and their lifestyles. AG Homes besides offers sales, letting, leasing of properties, land and property procurements for residential and commercial purposes.</p>
        </div>
        <div class="col-sm-12 col-md-4   py-3 ">
            <div class="box pb-4 pt-3 shadow">
                <img src="{% static '/images/man.jpeg' %}" class="d-block   ml-3  " alt="..."  class="shadow" style="width: 330px; height: 350px;">
            </div>
        </div>
    </div>z
</div>
<!-- ================================ -->
<!-- =======================our vision===================== -->
<div class="row mb-4 bg-light py-5">
  
    <div class="col-sm-12 col-md-8  text-center px-5 py-3 " >
        <h2 class="my-3">Our Vision</h2>
        <div class="tesimony p-5" >
            <p class="text-justify"> To become the leading Interior Design, Decoration and Real Estate Company where excellent standards are always maintained without shortcuts or short changing in Service delivery so as to meet the needs and demands of clients and teeming potential customers through offering expertise service delivery – a top-notch in all ramifications as it involves our products and services through a team of diligent, skilful,</p>

            <p class="text-justify p-2" style="border-left: 3px solid rgb(241, 145, 0) ;">
                experienced and restraint, distancing us from compromising on quality of products and services therefore making our brand indispensable, reliable, accessible, durable, available and affordable to customers at all times. We are poised to delivering top-notch products and services to suit every class of people and their lifestyles as well.
            </p>
            <hr>
          </div>
    </div>
    <!-- col-2 -->
    <div class="col-sm-12 col-md-4 text-center px-5 py-3 " >
        <h2 class="my-3">Our Integrity </h2>
        <div class="con-2  p-5"  style="background: #000;">
          <p class="text-center text-light" style="letter-spacing: 2;">We keep our word: we don't breach contracts and we give prompt delivery on all assigned duties or projects. We respond to orders as they come.</p>
          </div>
        </div>
      
  </div>
  
   
{% endblock main %}

aworld/templates/aworld/contact.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<style>
    *{
        text-decoration: none;
    }
    #enroll{
   background: url("/static/images/image-5.jpg");
   background-attachment: fixed;
   background-position: center;
   block-size: cover;
   background-repeat: no-repeat;
   background-size:cover;
   box-shadow:inset 0 0 0 2000px rgba(0,0,0,0.4);
   padding: 80px 0px;
   height: 400px;
  
  }

 #enroll h5{
    font-size: 20px;
    font-family: 'Castoro', serif;
    letter-spacing: 2;
    color:rgb(241, 145, 0) !important;
 }
 #enroll h5 a{
    text-decoration: none;
    color: #fff !important;
 }
 /* ====================== */
 

  #con-2{
      width:60%;
  }
  /* contact us  */
  /* form */

	.contact{
		padding: 4%;
		height: 400px;
	}
	.bb{
		background: rgb(241, 145, 0) ;
		padding: 4%;
		border-top-left-radius: 0.5rem;
		border-bottom-left-radius: 0.5rem;
	}
	.contact-info{
		margin-top:10%;
	}
	.contact-info img{
		margin-bottom: 15%;
	}
	.contact-info h2{
		margin-bottom: 10%;
	}
	.col-md-9{
		background: #fff;
		padding: 3%;
		border-top-right-radius: 0.5rem;
		border-bottom-right-radius: 0.5rem;
	}
	form label{
		font-weight:600;
	}
	form .form-group button{
		background: #25274d;
		color: #fff;
		font-weight: 600;
	
	}
	form .form-group button:focus{
		box-shadow:none;
	}
  /* form end */

  /* media screen */
  @media screen and (max-width:768px){

#con-2{
    width: 350px;
    height: 150px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50% , -50%);


  }
}
 
</style>

<!-- =============== -->
<div class="row mb-4 justify-content-center text-center">
    <div class="col-sm-12 " id="enroll">
      <div class="con-2 pt-5">
      <h3 class="text-light text-center lg-mt-5 text-justify " style="font-size: 30px;"> Contact Us </h3>
     <h5 class=" text-light" style="width: 70%; margin:auto;"> <a href="{% url 'aworld:index' %}">Home</a> |  Contact</h5>
      </div>
    </div>
</div>
<!-- ========================================= -->
<div class="container-fluid ">
    <div class="row my-2 justify-content-center text-center">
        <div class="col-sm-12 " id="section3">
          <marquee width="80%" direction="right" height="100px">
            <div class="con-2">
                <h3 class="animate__animated animate__fadeInUp animate__delay-1s text-center" style="font-weight: 900; color: #fff;"><span style="color: rgb(241, 145, 0) ;">Aword Greener Homes</span> </h3>
                 <p class="text-center a1">Tell us what you are looking for and we will try to get back to you as soon as possible.</p>
              </div>
          </marquee>
        </div>
    </div>
</div>
<!-- second row -->
<div class="container  my-5">
<div class="row">
    <div class="col-md-3 bb">
        <div class="contact-info">
            <img src="https://image.ibb.co/kUASdV/contact-image.png" alt="image"/>
            <h2>Contact Us</h2>
            <h4>We would love to hear from you !</h4>
  <p class="text text-light">Tel</p>
      <p class="text-light">
          +234 909-9347-874 <br> 
          +234 803 245 5940 <br>
         
      </p>
      
        </div>
    </div>
    <div class="col-md-9">
      <form method="post">
        {% csrf_token %}
				<div class="form-group">
				  <label class="control-label col-sm-2" for="fname">Full Name:</label>
				  <div class="col-sm-10">          
					<input type="text" class="form-control"  placeholder="Enter Full Name" name="fname" required>
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="email">Email:</label>
				  <div class="col-sm-10">
					<input type="email" class="form-control"  placeholder="Enter email" name="email" required>
				  </div>
				</div>
				<div class="form-group">
				  <label class="control-label col-sm-2" for="comment">Message:</label>
				  <div class="col-sm-10">
					<textarea class="form-control" rows="5"  name="comment"></textarea>
				  </div>
				</div>
				<div class="form-group">        
				  <div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-default">Send Message</button>
				  </div>
				</div>
    </form>
    </div>
</div>
</div>
<!-- the ota map -->
<div class="container-fluid my-5 shadow">
<div class="row">
<div class="col-sm-12">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3962.638764663732!2d3.2449811142670786!3d6.691586523044166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103b99ca0197b4ed%3A0x3dcc5b991693734!2sIlo%20Awela%20Rd%2C%20Ota!5e0!3m2!1sen!2sng!4v1624887657651!5m2!1sen!2sng" width="100%" height="550" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>
</div>
</div>

<!-- ======================================= -->

{% endblock main %}

aworld/templates/aworld/email_sent.html
{% extends 'base.html' %}
{% load static %} 
{% block main %}

<style>
    #section3{
     background: url("/static/images/bed.jpg");
     background-attachment: fixed;
     background-position: center;
     block-size: cover;
     background-repeat: no-repeat;
     width: 100%;
     height: 500px;
     margin-bottom: 25px ;
     min-height:100%;
     background-size:cover;
     box-shadow:inset 0 0 0 2000px rgba(0,0,0,0.7);
     padding: 80px 0px;
    }
 
    #section3 h3{
      font-family: 'Josefin Sans', sans-serif;
      font-size: 35px;
      font-weight: 600;
      margin-top: 80px;
      
    }
    #section3 p{
     margin:auto;
     font-size: 15px; 
     font-family: 'Charm', cursive;
     letter-spacing: 2px;
     color:#fff;
     line-height: 25px;
   }
 
   #con-2{
       width:60%;
   }
   /* contact us  */
   /* form */
 
     .contact{
         padding: 4%;
         height: 400px;
     }
     .bb{
         background: #ff9b00;
         padding: 4%;
         border-top-left-radius: 0.5rem;
         border-bottom-left-radius: 0.5rem;
     }
     .contact-info{
         margin-top:10%;
     }
     .contact-info img{
         margin-bottom: 15%;
     }
     .contact-info h2{
         margin-bottom: 10%;
     }
     .col-md-9{
         background: #fff;
         padding: 3%;
         border-top-right-radius: 0.5rem;
         border-bottom-right-radius: 0.5rem;
     }
     form label{
         font-weight:600;
     }
     form .form-group button{
         background: #25274d;
         color: #fff;
         font-weight: 600;
     
     }
     form .form-group button:focus{
         box-shadow:none;
     }
   /* form end */
 
   /* media screen */
   @media screen and (max-width:768px){
 
 #con-2{
     width: 350px;
     height: 150px;
     position: absolute;
     top: 50%;
     left: 50%;
     transform: translate(-50% , -50%);
 
 
   }
 }
 </style>
      <div class="container-fluid ">
         <div class="row my-2 justify-content-center text-center">
             <div class="col-sm-12 " id="section3">
               <div class="con-2">
                 <h3 class="animate__animated animate__fadeInUp animate__delay-1s text-center" style="font-weight: 900; color: #fff;"><span style="color: #fc721e;">Aworld Greener</span> Homes</h3>
                  <p class="text-center a1">Thank you, You just send an email with:{{email}} and we will try and get back to you as soon as possible.</p>
               </div>
             </div>
         </div>
     </div>
 

{% endblock  %}

aworld/templates/aworld/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<style>
    *{
        text-decoration: none;
    }
    #enroll{
   background: url("/static/images/image-5.jpg");
   background-attachment: fixed;
   background-position: center;
   block-size: cover;
   background-repeat: no-repeat;
   background-size:cover;
   box-shadow:inset 0 0 0 2000px rgba(0,0,0,0.4);
   padding: 80px 0px;
   height: 400px;
  
  }

 #enroll h5{
    font-size: 20px;
    font-family: 'Castoro', serif;
    letter-spacing: 2;
    color:rgb(241, 145, 0) !important;
 }
 #enroll h5 a{
    text-decoration: none;
    color: #fff !important;
 }
 /* ============our servuce ================ */
 /* gallery */
 .col2{margin-top: 100px;}
    .item {
         margin-bottom: 30px
     }
    
     .item .box {
         text-align: center;
         background-repeat: no-repeat;
         background-size: cover;
         background-position: center;
         
         position: relative;
         overflow: hidden;
     }
    
     .item .cover {
         position: absolute;
         top: 0;
         left: 0;
         width: 100%;
         height: 100%;
         background-color: rgba(0, 0, 0, 0.5);
         transition: opacity 0.15s ease-in;
         opacity: 0;
         padding-top: 80px;
         color: #fff;
         text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.15)
     }
    
     .item:hover .cover {
         opacity: 1
     }
    

 
   
</style>

<!-- =============== -->
<div class="row mb-4 justify-content-center text-center">
    <div class="col-sm-12 " id="enroll">
      <div class="con-2 pt-5">
      <h3 class="text-light text-center lg-mt-5 text-justify " style="font-size: 30px;"> Gallery</h3>
     <h5 class=" text-light" style="width: 70%; margin:auto;"> <a href="{% url 'aworld:index' %}">Home</a> |  Gallery</h5>
      </div>
    </div>
</div>
<!-- ====================our story=================================== -->
<div class="container-fluid" style="margin-top: 90px; margin-bottom:90px ;">
    <div class="container">
      <div class="row">
        {% for g in gallery %}
          <div class="col-sm-12 col-md-4 my-2 item" data-aos="flip-right">
            <div class="box">
              <img  class="card-image-top animate__animated animate__fadeInUp animate__delay-1s" src="{{ g.image.url }}" width="100%" class="d-block w-100" >
              <div class="cover text-center">
                <h2>{{ g.type_of_image}}</h2>
                <p>{{ g.content |truncatechars:"40"}}</p>
             </div>
            </div>
          </div>
          {% endfor %}
      </div>
    </div>
  </div>
  <!-- quote end  -->

{% endblock main %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<title>Aword Greener Homes | aworld decoration | aworld design | real estate |</title>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<!-- Stylesheets -->





<!-- ==============google font============ -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Castoro:ital@1&display=swap" rel="stylesheet">
<!-- ======================================================= -->
<!-- animate css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
<!-- ========================CUSTOM CSS================================== -->
<link rel="stylesheet" href="{% static '/css/base.css' %}">
<!-- =================== -->
<!-- fontawsome key -->
<script src="https://kit.fontawesome.com/e6bc8b7e05.js" crossorigin="anonymous"></script>

</head>

<body>
    
    <!-- =======================navbar======================= -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top bgcolor">
    <div class="container">
    <a class="navbar-brand text-light" href="{%  url 'aworld:index' %}"><img src="{% static '/images/awordre.png' %}" alt="" style="width: 110px; height: 50px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{%  url 'aworld:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'aworld:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%  url 'aworld:gallery' %}">Gallery</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'aworld:service' %}">Service</a>
      </li>
        
        <li class="nav-item eportal">
          <a class="nav-link" href="{%  url 'aworld:contact' %}">Contact</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item con">
          <a class="nav-link" href="/admin/login/?next=/admin/">Admin Login</a>
        </li>
        {% endif %}
       
      </ul>
    </div>
</div>
  </nav>
<!-- ================================end nabv============ -->

{% block main %} 

{% endblock main %}


<!-- ================================FOOTER================================ -->
<footer>
  <div class="footer-top">
    <div class="container">
      <div class="row mb-4">

        <div class="col-md-3 col-sm-6 col-xs-12 segment-one md-mb-30 sm-mb-30 mb-4">
          <img src="{% static '/images/awordre.png' %}" alt="" style="width: 110px; height: 50px;">
        </div>

        <div class="col-md-3 col-sm-6 col-xs-12 segment-two md-mb-30 sm-mb-30 mb-4">
          <h2 class="my-3">Gallery Info</h2>
        <ul>
          <li><a href="{%  url 'aworld:about' %}">About</a></li>
          <li><a href="{%  url 'aworld:service' %}">Service</a></li>
          <li><a href="{% url 'aworld:contact' %}">Contact</a></li>
        </ul>
        </div>

        <div class="col-md-3 col-sm-6 col-xs-12 segment-three md-mb-30 sm-mb-30 mb-4">
          <h2 class="my-3">Follow Us</h2>
          <p> 2/3 Ilo-Awela Road, off Tollgate, Otta, Ogun/Lagos states, Nigeria.</p>
          <a href="#"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a> 
          <a href="#"><i class="fa fa-instagram"></i></a>        
        </div>

        

        <div class="col-md-3 col-sm-6 col-xs-12 segment-two md-mb-30 sm-mb-30 mb-4">
          <h2 class="my-3">Contact</h2>

          <ul>
            <li><span style="font-weight: bold; margin-right: 5px; font-size: 15px; color:rgb(241, 145, 0); "><i class="fas fa-envelope"></i></span><a  href = "mailto: greenerhomes2020@gmail.com"> greenerhomes2020@gmail.com</a></li>
             <li><span style="font-weight: bold; margin-right: 5px; font-size: 15px; color:rgb(241, 145, 0); "><i class="fas fa-envelope"></i></span><a  href = "mailto: greenerhomes2020@gmail.com"> aworldgreenerhomes@yahoo.com</a></li>
            <li><span style="font-weight: bold; margin-right: 5px; font-size: 15px; color: rgb(241, 145, 0);"><i class="fas fa-phone"></i></span>+234 803 245 5940 </li>
            <li><span style="font-weight: bold; margin-right: 5px; font-size: 15px; color: rgb(241, 145, 0);"><i class="fas fa-phone"></i></span>+234 909 934 7874 </li>
          </ul>
        </div>
        
      </div>
    </div>
  </div>
  <p class="footer-bottom-text">All Right reserved by &copy; <script>document.write(new Date().getFullYear());</script> Aworld Greener Homes.</p>
</footer>
<!-- ================================ END FOOTER================================ -->

<!--=============== custom js ============== -->


<script src="{% static '/js/index.js' %}"></script>


<!-- ================================= -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>


<script>

  $(window).scroll(function(){
      $('nav').toggleClass('scrolled', $(this).scrollTop()>50);
  });

</script>


</body>
</html>